FROM node:25-alpine AS builder

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    CYPRESS_INSTALL_BINARY=0

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build


FROM nginx:stable-alpine-slim

RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
