FROM node:25-alpine AS constructor

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    CYPRESS_INSTALL_BINARY=0

WORKDIR /app

COPY package.json package-lock.json ./
RUN /usr/local/bin/npm ci

COPY . .

RUN /usr/local/bin/npm run build


FROM nginx:stable-alpine-slim

COPY --from=constructor /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
