name: Docker Image CI

on:
    push:
        branches: ["ci-cd"]

env:
    ENVIRONMENT: development
    AWS_REGION: us-east-1

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Configure AWS Credentials 2
              uses: aws-actions/configure-aws-credentials@v6.0.0
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: get caller identity2
              run: |
                  aws sts get-caller-identity

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and tag docker image to Amazon ECR
              env:
                  REGISTRY: ${{  vars.REGISTRY_URI }}
                  REPOSITORY: ${{ vars.APP_NAME }}
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" -f Dockerfile.optimizado .
                  docker tag "$REGISTRY/$REPOSITORY:$IMAGE_TAG" "$REGISTRY/$REPOSITORY:latest"

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@0.33.1
              env:
                  ACTIONS_STEP_DEBUG: true
              with:
                  image-ref: "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
                  format: "table"
                  exit-code: "1"
                  ignore-unfixed: true
                  vuln-type: "os,library"
                  severity: "CRITICAL,HIGH"

            - name: Push docker image to Amazon ECR
              env:
                  REGISTRY: ${{  vars.REGISTRY_URI }}
                  REPOSITORY: ${{ vars.APP_NAME }}
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
                  docker push "$REGISTRY/$REPOSITORY:latest"
    deploy:
        runs-on: ubuntu-latest
        needs: [build-and-push]
        steps:
            - name: Configure AWS Credentials 2
              uses: aws-actions/configure-aws-credentials@v6.0.0
              with:
                  aws-region: ${{ env.AWS_REGION }}
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: get caller identity2
              run: |
                  aws sts get-caller-identity
            - name: Update service
              run: |
                  aws ecs update-service --cluster test-bootcamperu --service bootcamperu-service-kejfq6rq --task-definition arn:aws:ecs:us-east-1:301820662531:task-definition/bootcamperu:4
